### ISSUE TITLE
Import error when running pheval

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/pheval#369]
When I run pheval, I see this stacktrace coming ultimately from linkml_runtime I think 

`ImportError: cannot import name 're' from 'typing' (/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/typing.py)`

Here's the full stacktrace:
```
(.venv) ~/PythonProject/exomiser-reranking main $ pheval 
Traceback (most recent call last):
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/bin/pheval", line 5, in <module>
    from pheval.cli import pheval
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/pheval/cli.py", line 8, in <module>
    from .cli_pheval_utils import (
    ...<8 lines>...
    )
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/pheval/cli_pheval_utils.py", line 11, in <module>
    from pheval.prepare.create_noisy_phenopackets import scramble_phenopackets
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/pheval/prepare/create_noisy_phenopackets.py", line 5, in <module>
    from oaklib.implementations.pronto.pronto_implementation import ProntoImplementation
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/oaklib/__init__.py", line 8, in <module>
    from oaklib.interfaces import BasicOntologyInterface  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/oaklib/interfaces/__init__.py", line 1, in <module>
    from oaklib.interfaces.basic_ontology_interface import BasicOntologyInterface
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/oaklib/interfaces/basic_ontology_interface.py", line 14, in <module>
    from sssom.parsers import parse_sssom_table, to_mapping_set_document
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/sssom/__init__.py", line 11, in <module>
    from sssom_schema import Mapping, MappingSet, slots  # noqa:401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/sssom_schema/__init__.py", line 1, in <module>
    from .datamodel.sssom_schema import *
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/sssom_schema/datamodel/sssom_schema.py", line 15, in <module>
    from linkml_runtime.linkml_model.meta import EnumDefinition, PermissibleValue, PvFormulaOptions
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/linkml_runtime/__init__.py", line 3, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/linkml_runtime/utils/schemaview.py", line 17, in <module>
    from linkml_runtime.linkml_model.meta import *
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/linkml_runtime/linkml_model/__init__.py", line 1, in <module>
    from .types import String, Integer, Boolean, Float, Double, Decimal, Time, Date, Datetime, Uriorcurie, Uri, \
        Ncname, Objectidentifier, Nodeidentifier
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/linkml_runtime/linkml_model/types.py", line 15, in <module>
    from linkml_runtime.utils.slot import Slot
  File "/Users/jtr4v/PythonProject/exomiser-reranking/.venv/lib/python3.13/site-packages/linkml_runtime/utils/slot.py", line 2, in <module>
    from typing import Type, List, Optional, Any, re
ImportError: cannot import name 're' from 'typing' (/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/typing.py)
```

I'm on python3.13 for arm64, and pheval 0.4.1 installed via pip

```
(.venv) $ python --version 
Python 3.13.0
(.venv) $ pip freeze | grep pheval 
pheval==0.4.1
(.venv)  $ file `which python`
Mach-O 64-bit executable arm64
```

**Comment by justaddcoffee** [comment]
Adding: this isn't a pheval bug per se, just thought it might be worth making this ticket in case you want to pin to a different version of linkml_runtime to prevent this?
